"""labimprove — stage-only candidate generator + safety tests (SI-027, SI-028).

Per roadmap section 23 / SI-027 + SI-028, this module stages candidate
skill changes to ``improvement/candidates/<id>/`` (gitignored) and runs
safety tests on them. **Candidates are never applied to live skills.**
Promotion to a live skill is a human action (SI-029, future).

The two public entry points are:

  - ``stage_candidate(...)`` — write a candidate's patch, metadata, and
    rollback artifact to ``improvement/candidates/<id>/``. Returns the
    candidate metadata dict. Does NOT apply the patch to the live
    skill. The candidate stays staged until a human approves it.

  - ``run_safety_tests(candidate_id, ...)`` — run the SI-028 safety
    test suite on a staged candidate. Returns
    ``{"passed": bool, "tests": [...], "hard_failure": bool}``. A single
    hard_failure = instant rejection (the candidate cannot be
    promoted, regardless of any other quality signal).

Design rules (per roadmap section 14 + ADR-0001):

  - **Default-deny mutation.** The allowlist
    (``improvement/policy/mutation-allowlist.yaml``) lists every file a
    candidate MAY modify. Everything else is denied. ``scope/SKILL.md``
    and all TCB paths are explicitly excluded. The allowlist itself is
    TCB — the candidate may read it but never modify it.

  - **Stage-only.** ``stage_candidate`` writes to
    ``improvement/candidates/<id>/`` (gitignored per SI-000). It never
    touches the live skill. The live skill is only modified by a
    human-approved promotion (SI-029, future).

  - **Reverse diff as rollback.** For every staged candidate, we also
    write ``rollback.patch`` — the reverse unified diff that would
    undo the change. This is generated by computing the diff in the
    opposite direction (swap ``+`` and ``-`` lines). It's a
    best-effort artifact; the canonical rollback is "git checkout" on
    the live skill, but the reverse diff is useful for review and for
    restoring a copy in a non-git context.

  - **No network, no subprocess.** This module is pure Python — it
    reads files, writes files, and parses diffs. It never spawns a
    subprocess and never touches the network. This makes it safe to
    run inside the evaluation sandbox (ADR-0003) and easy to test.

  - **Provenance is mandatory.** Every staged candidate carries a
    ``provenance.json`` with session, agent, model, timestamp. This is
    for auditability — every change to a skill must be traceable to a
    specific run, agent, and model.

Safety tests (SI-028):

  1. **MUT-001** Patch only modifies allowlisted files (uses
     ``mutation_check.validate_candidate_patch``).
  2. **MUT-002** Patch does not touch any safety-critical path
     (``denied_safety_critical`` in the allowlist). This is a subset
     of #1 but is checked separately so a safety-critical violation is
     reported with its own reason.
  3. **SIZE-001** Patch does not increase cyclomatic complexity beyond
     the ceiling (``complexity_ceiling: 15`` in
     ``improvement/config/optimization.yaml``). The ceiling is the
     maximum DELTA, not the absolute value.
  4. **SIZE-002** Patch does not exceed ``max_candidate_diff_size``
     (50000 chars).
  5. **SIZE-003** Modified skill does not exceed ``max_skill_length``
     (50000 chars after patch).
  6. **LEAK-001** Patch does not contain any string from
     ``evals/**/private/labels.json`` or ``improvement/private/`` (if
     those files exist). A patch that contains a private label string
     is strong evidence the candidate read private evaluation data.

Tests #1 and #2 are hard-failure (safety-critical). Tests #3–#5 are
hard-failure (budget/complexity). Test #6 is hard-failure (leakage).
A single hard-failure = instant rejection.

This module is TCB (per ADR-0001). The candidate may read it but never
modify it.
"""

from __future__ import annotations

import hashlib
import json
import re
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Local import — mutation_check is in the same lib/ directory.
import mutation_check as MC
import yaml

# ─── Constants ─────────────────────────────────────────────────────────────────

CANDIDATES_DIR = "improvement/candidates"  # gitignored per SI-000 / .gitignore

# Repo-relative paths to TCB files (used by run_safety_tests to find
# the allowlist and config without needing a repo-root argument).
DEFAULT_ALLOWLIST_REL = "improvement/policy/mutation-allowlist.yaml"
DEFAULT_CONFIG_REL = "improvement/config/optimization.yaml"

# Default safety-test limits (used only if the config file is missing
# or a key is absent — defense-in-depth so tests don't crash on a
# fresh install that hasn't been fully configured).
_DEFAULT_COMPLEXITY_CEILING = 15
_DEFAULT_MAX_DIFF_SIZE = 50000
_DEFAULT_MAX_SKILL_LENGTH = 50000


# ─── Helpers ───────────────────────────────────────────────────────────────────


def _now_iso() -> str:
    """Current UTC time as ISO 8601 with ``Z`` suffix (e.g. 2026-07-19T12:34:56Z)."""
    return datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256_text(text: str) -> str:
    """Hex sha256 of a string (UTF-8 encoded)."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _repo_root_from(anchor: Path) -> Path:
    """Find the repo root from an anchor path.

    Walks up from ``anchor`` looking for ``improvement/policy/`` (which
    exists in every install of the lab). Falls back to ``anchor``'s
    parents until it finds one that contains
    ``improvement/policy/mutation-allowlist.yaml``.
    """
    anchor = anchor.resolve()
    for cand in [anchor, *anchor.parents]:
        if (cand / DEFAULT_ALLOWLIST_REL).is_file():
            return cand
    # Fall back to the anchor itself — callers will get a FileNotFoundError
    # when they try to load the allowlist, which is a clear signal.
    return anchor


def _apply_patch_to_text(text: str, patch: str) -> str:
    """Apply a unified diff to text and return the result.

    This is a minimal unified-diff applier. It handles the common case
    of a single-hunk patch against a known base. It is NOT a full
    ``patch(1)`` implementation — it does not handle:

      - context line fuzz (lines that match with whitespace differences)
      - offset adjustment (hunks applied at a different line than stated)
      - multiple files in one patch (callers apply one file at a time)
      - binary patches

    For the safety tests, we only need an approximate "what would the
    skill look like after this patch" to measure its length. A
    precise apply is the job of ``git apply`` at promotion time
    (SI-029), not at staging time.

    Strategy: parse hunks (``@@ -start,len +start,len @@``), and for
    each hunk, replace the lines that start with ``-`` (removed) with
    the lines that start with ``+`` (added), keeping context lines
    (leading space) as-is. We use the hunk's ``-start`` to find the
    insertion point in the current text.

    Raises ValueError if the patch is malformed or the context lines
    don't match the base text at the stated offset. The caller (safety
    tests) treats this as a failed apply — the skill-length test
    reports "could not apply patch" and the candidate fails.
    """
    lines = text.splitlines(keepends=False)
    out = list(lines)
    offset_shift = 0  # accumulated line shift from earlier hunks

    hunks: list[tuple[int, int, list[str]]] = []  # (old_start, old_len, body_lines)
    cur_hunk: tuple[int, int, list[str]] | None = None

    for line in patch.splitlines():
        if line.startswith("@@"):
            if cur_hunk is not None:
                hunks.append(cur_hunk)
            m = re.match(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@", line)
            if not m:
                raise ValueError(f"malformed hunk header: {line!r}")
            old_start = int(m.group(1))
            old_len = int(m.group(2)) if m.group(2) is not None else 1
            cur_hunk = (old_start, old_len, [])
        elif cur_hunk is not None and (
            line.startswith(" ") or line.startswith("+") or line.startswith("-")
            or line == ""
        ):
            # Empty lines within a hunk are context lines (a leading
            # space would be present in a strict diff, but some tools
            # omit it for empty context lines).
            cur_hunk[2].append(line)
        elif line.startswith(("---", "+++", "diff ", "index ")):
            # File header — ignore. We already know which file this is.
            continue
        else:
            # Unknown line — end the current hunk.
            if cur_hunk is not None:
                hunks.append(cur_hunk)
                cur_hunk = None

    if cur_hunk is not None:
        hunks.append(cur_hunk)

    for old_start, old_len, body in hunks:
        # Separate body into removed, added, context.
        removed: list[str] = []
        added: list[str] = []
        context: list[str] = []
        for bline in body:
            if bline.startswith("-"):
                removed.append(bline[1:])
            elif bline.startswith("+"):
                added.append(bline[1:])
            else:
                # Context line (leading space stripped) or empty line.
                ctx = bline[1:] if bline.startswith(" ") else bline
                context.append(ctx)
                removed.append(ctx)  # context is in both old and new
                added.append(ctx)

        # Find the insertion point. old_start is 1-based; 0 means "prepend
        # before line 1" (used for file creation).
        start_idx = 0 if old_start == 0 else old_start - 1 + offset_shift

        # Verify the context matches (best-effort — if old_len > 0 we
        # expect the removed lines to match the base at start_idx).
        # Check at least the first removed line matches (when there
        # are removed lines; pure-add hunks have old_len = 0).
        if old_len > 0 and 0 <= start_idx < len(out) and removed and removed[0] != out[start_idx]:
            # Context mismatch — try to find the right offset by
            # searching nearby. This is a very small fuzz tolerance.
            found = -1
            for delta in range(-5, 6):
                idx = start_idx + delta
                if 0 <= idx < len(out) and removed[0] == out[idx]:
                    found = idx
                    break
            if found < 0:
                raise ValueError(
                    f"context mismatch at line {old_start}: "
                    f"expected {removed[0]!r}, got {out[start_idx]!r}"
                )
            start_idx = found

        # Replace the range [start_idx, start_idx + old_len) with added.
        end_idx = start_idx + old_len
        out[start_idx:end_idx] = added
        offset_shift += len(added) - old_len

    return "\n".join(out)


def _reverse_patch(patch: str) -> str:
    """Produce a reverse unified diff (swap + and - lines).

    This is a best-effort rollback artifact. For a unified diff::

        --- a/PATH
        +++ b/PATH
        @@ -1,3 +1,3 @@
         context
        -old
        +new
         context

    The reverse is::

        --- a/PATH
        +++ b/PATH
        @@ -1,3 +1,3 @@
         context
        -new
        +old
         context

    Hunk headers are rewritten to swap the ``-`` and ``+`` ranges. File
    headers (``--- a/PATH`` / ``+++ b/PATH``) are swapped. ``diff --git``
    lines are preserved (they're symmetric).

    Lines that start with ``+`` become ``-`` and vice versa. Context
    lines (leading space) are preserved. Empty lines are preserved.
    """
    out: list[str] = []
    for line in patch.splitlines():
        if line.startswith("@@"):
            m = re.match(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@", line)
            if m:
                old_s, old_l, new_s, new_l = m.groups()
                old_l = old_l or "1"
                new_l = new_l or "1"
                out.append(f"@@ -{new_s},{new_l} +{old_s},{old_l} @@")
                continue
            out.append(line)
        elif line.startswith("+++") or line.startswith("---"):
            # Swap +++ and ---.
            if line.startswith("+++"):
                out.append("-" + line[1:])
            else:
                out.append("+" + line[1:])
        elif line.startswith("+"):
            out.append("-" + line[1:])
        elif line.startswith("-"):
            out.append("+" + line[1:])
        else:
            out.append(line)
    return "\n".join(out)


# ─── stage_candidate ───────────────────────────────────────────────────────────


def stage_candidate(
    skill_path: Path,
    patch: str,
    linked_lessons: list[str],
    evaluation_summary: str = "",
    provenance: dict | None = None,
    candidates_dir: Path | None = None,
) -> dict:
    """Stage a candidate skill change. Never applies to live skills.

    Creates ``improvement/candidates/<candidate-id>/`` with:

    - ``skill.patch`` — the unified diff (the change).
    - ``linked-lessons.json`` — lesson IDs that motivated this change.
    - ``evaluation-summary.md`` — human-readable summary.
    - ``safety-checklist.md`` — to be filled by safety tests (initially
      a placeholder with the test names listed).
    - ``rollback.patch`` — the reverse diff (how to undo).
    - ``provenance.json`` — session, agent, model, timestamp.
    - ``metadata.json`` — the candidate metadata (same dict returned
      by this function, written to disk for later loading).

    Args:
        skill_path: repo-relative path to the skill being modified
            (e.g. ``skills/security/bounty-attack/SKILL.md``). May be
            absolute or relative. Stored as a POSIX-style relative path
            in the metadata.
        patch: the unified diff. Must be a string (not bytes).
        linked_lessons: lesson IDs that motivated this change. Stored
            as a JSON list.
        evaluation_summary: human-readable summary of the evaluation
            that produced this candidate. Markdown-formatted.
        provenance: dict with ``session``, ``agent``, ``model``,
            ``timestamp`` keys (any subset is fine; missing keys are
            filled with defaults). Used for auditability.
        candidates_dir: override the candidates directory (for
            testing). Defaults to ``<repo>/improvement/candidates/``.

    Returns:
        The candidate metadata dict::

            {
              "candidate_id": "<uuid4>",
              "staged_at": "<ISO 8601 UTC>",
              "skill_path": "skills/security/bounty-attack/SKILL.md",
              "patch_sha256": "<hex>",
              "linked_lessons": [...],
              "provenance": {...}
            }

    Never applies the patch to the live skill. The candidate stays
    staged until a human approves it (SI-029).
    """
    candidate_id = str(uuid.uuid4())
    staged_at = _now_iso()
    patch_sha256 = _sha256_text(patch)

    # Normalize the skill path to a repo-relative POSIX string.
    skill_path_str = str(skill_path).strip()
    while skill_path_str.startswith("./"):
        skill_path_str = skill_path_str[2:]

    # Resolve candidates_dir.
    if candidates_dir is None:
        anchor = Path(skill_path).resolve() if Path(skill_path).is_absolute() else Path.cwd()
        repo_root = _repo_root_from(anchor)
        candidates_dir = repo_root / CANDIDATES_DIR
    candidates_dir = Path(candidates_dir)
    candidate_dir = candidates_dir / candidate_id
    candidate_dir.mkdir(parents=True, exist_ok=True)

    # Provenance with defaults.
    prov = provenance or {}
    prov_full = {
        "session": prov.get("session", ""),
        "agent": prov.get("agent", ""),
        "model": prov.get("model", ""),
        "timestamp": prov.get("timestamp", staged_at),
    }

    metadata = {
        "candidate_id": candidate_id,
        "staged_at": staged_at,
        "skill_path": skill_path_str,
        "patch_sha256": patch_sha256,
        "linked_lessons": list(linked_lessons),
        "provenance": prov_full,
    }

    # Write artifacts.
    (candidate_dir / "skill.patch").write_text(patch, encoding="utf-8")
    (candidate_dir / "linked-lessons.json").write_text(
        json.dumps(list(linked_lessons), indent=2) + "\n", encoding="utf-8"
    )
    summary_text = evaluation_summary
    if summary_text and not summary_text.endswith("\n"):
        summary_text += "\n"
    (candidate_dir / "evaluation-summary.md").write_text(summary_text, encoding="utf-8")
    (candidate_dir / "rollback.patch").write_text(_reverse_patch(patch), encoding="utf-8")
    (candidate_dir / "provenance.json").write_text(
        json.dumps(prov_full, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (candidate_dir / "metadata.json").write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    # Safety-checklist placeholder. run_safety_tests() will overwrite
    # this with the actual test results.
    checklist_lines = [
        "# Safety checklist — candidate " + candidate_id,
        "",
        "Staged at: " + staged_at,
        "Skill: " + skill_path_str,
        "",
        "## Safety tests (run by labimprove.run_safety_tests)",
        "",
        "- [ ] MUT-001: patch only modifies allowlisted files",
        "- [ ] MUT-002: patch does not touch safety-critical paths",
        "- [ ] SIZE-001: complexity under ceiling",
        "- [ ] SIZE-002: diff size under limit",
        "- [ ] SIZE-003: skill length under limit",
        "- [ ] LEAK-001: no private label access",
        "",
        "Status: PENDING (run_safety_tests has not been called yet).",
    ]
    (candidate_dir / "safety-checklist.md").write_text(
        "\n".join(checklist_lines) + "\n", encoding="utf-8"
    )

    return metadata


# ─── run_safety_tests ──────────────────────────────────────────────────────────


def _load_optimization_config(config_path: Path) -> dict[str, int]:
    """Load optimization config, returning the relevant limits.

    Returns a dict with keys ``complexity_ceiling``, ``max_diff_size``,
    ``max_skill_length``. Missing keys fall back to the module defaults.
    Missing file → all defaults.
    """
    out = {
        "complexity_ceiling": _DEFAULT_COMPLEXITY_CEILING,
        "max_diff_size": _DEFAULT_MAX_DIFF_SIZE,
        "max_skill_length": _DEFAULT_MAX_SKILL_LENGTH,
    }
    if not config_path.is_file():
        return out
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return out
    opt = data.get("optimization") if isinstance(data, dict) else None
    if not isinstance(opt, dict):
        return out
    for k in out:
        v = opt.get(k)
        if isinstance(v, int | float):
            out[k] = int(v)
    return out


def _cyclomatic_complexity(text: str) -> int:
    """Estimate cyclomatic complexity of a Markdown/text file.

    For Markdown skill files, true cyclomatic complexity (in the
    McCabe sense) doesn't apply — there's no control flow graph. We
    use a proxy: the count of decision-point keywords that indicate
    branching logic in the skill's instructions. These are the
    keywords an agent following the skill would treat as a branch:

      - ``if``, ``unless``, ``when``, ``while``, ``for``
      - ``case``, ``switch`` (rare in prose, but present in code blocks)
      - ``try``, ``except``, ``catch`` (in embedded code blocks)

    This is a rough proxy but it's good enough to catch a candidate
    that adds a giant branching decision tree to a skill. The ceiling
    is on the DELTA (increase), not the absolute value, so a skill
    that's already complex doesn't fail just for being complex — it
    fails only if the candidate makes it MORE complex.

    The count is case-insensitive, word-bounded (``\b``) so "if" inside
    a word like "device" doesn't count.
    """
    pattern = re.compile(
        r"\b(if|unless|when|while|for|case|switch|try|except|catch)\b",
        re.IGNORECASE,
    )
    return len(pattern.findall(text))


def _collect_private_label_strings(repo_root: Path) -> set[str]:
    """Collect strings that are private evaluation labels.

    Scans:
      - ``evals/**/private/labels.json`` (private eval labels, gitignored)
      - ``improvement/private/`` (real outcomes, gitignored)

    Returns a set of strings. For JSON files, we recursively walk the
    structure and collect all string values (these are the labels
    themselves — case IDs, expected verdicts, etc.). For YAML files,
    same. For other files, we read line by line and collect any
    non-trivial string (>= 4 chars, alphanumeric).

    A candidate patch that contains ANY of these strings is presumed
    to have read private data. This is defense-in-depth: the
    evaluation sandbox already blocks file reads outside the
    candidate's scratch dir (ADR-0003), but this catches accidents.

    Returns an empty set if no private dirs exist (e.g. on a fresh
    install that hasn't been populated). The leakage test is then a
    no-op (vacuously passes).
    """
    out: set[str] = set()

    # evals/**/private/labels.json
    for p in repo_root.glob("evals/**/private/labels.json"):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        _collect_strings(data, out)

    # improvement/private/** — walk all files.
    priv = repo_root / "improvement" / "private"
    if priv.is_dir():
        for p in priv.rglob("*"):
            if not p.is_file():
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            # Try JSON first, then YAML, then line-by-line.
            try:
                data = json.loads(text)
                _collect_strings(data, out)
                continue
            except (OSError, json.JSONDecodeError):
                pass
            try:
                data = yaml.safe_load(text)
                if isinstance(data, dict | list):
                    _collect_strings(data, out)
                    continue
            except (OSError, yaml.YAMLError):
                pass
            # Line-by-line: collect non-trivial strings.
            for line in text.splitlines():
                s = line.strip()
                if len(s) >= 4 and re.search(r"[A-Za-z0-9]", s):
                    out.add(s)

    return out


def _collect_strings(obj: Any, out: set[str]) -> None:
    """Recursively walk a JSON/YAML structure, collecting string values."""
    if isinstance(obj, str):
        if len(obj) >= 4 and re.search(r"[A-Za-z0-9]", obj):
            out.add(obj)
    elif isinstance(obj, dict):
        for v in obj.values():
            _collect_strings(v, out)
    elif isinstance(obj, list):
        for v in obj:
            _collect_strings(v, out)


def _check_leakage(patch: str, label_strings: set[str]) -> tuple[bool, str]:
    """Check if the patch contains any private label string.

    Returns ``(is_leak, detail)``. If ``is_leak`` is True, ``detail`` is
    the first matched string (truncated for the report). If False,
    ``detail`` is the empty string.

    We check each label string as a substring of the patch (not as a
    whole line) — a candidate that embeds a private label in a comment
    or a variable name still leaks it. We require the label to be at
    least 4 chars to avoid false positives on common short strings.
    """
    for s in label_strings:
        if s in patch:
            return True, s[:80]
    return False, ""


def run_safety_tests(
    candidate_id: str,
    candidates_dir: Path | None = None,
    allowlist_path: Path | None = None,
    config_path: Path | None = None,
    repo_root: Path | None = None,
) -> dict:
    """Run safety tests on a staged candidate.

    Args:
        candidate_id: the candidate UUID (matches the directory name
            under ``candidates_dir``).
        candidates_dir: override the candidates directory (for
            testing). Defaults to ``<repo>/improvement/candidates/``.
        allowlist_path: override the allowlist path (for testing).
            Defaults to ``<repo>/improvement/policy/mutation-allowlist.yaml``.
        config_path: override the optimization config path (for
            testing). Defaults to ``<repo>/improvement/config/optimization.yaml``.
        repo_root: override the repo root (for testing). Defaults to
            the repo containing the allowlist.

    Returns:
        ``{"passed": bool, "tests": [...], "hard_failure": bool}``.

        ``passed`` is True iff every test passed. ``hard_failure`` is
        True iff any safety-critical test failed (MUT-001, MUT-002,
        LEAK-001, or any SIZE test). When ``hard_failure`` is True,
        ``passed`` is False — a hard failure cannot be a pass.

        Each entry in ``tests`` is::

            {
              "name": "MUT-001",
              "description": "patch only modifies allowlisted files",
              "passed": bool,
              "detail": "...",     # human-readable explanation
              "hard_failure": bool # does this test's failure = hard failure?
            }
    """
    # Resolve paths.
    if allowlist_path is None:
        # Find the repo root from candidates_dir if given, else cwd.
        if candidates_dir is not None:
            repo_root = repo_root or _repo_root_from(Path(candidates_dir))
        else:
            repo_root = repo_root or _repo_root_from(Path.cwd())
        allowlist_path = Path(repo_root) / DEFAULT_ALLOWLIST_REL
        config_path = config_path or (Path(repo_root) / DEFAULT_CONFIG_REL)
        if candidates_dir is None:
            candidates_dir = Path(repo_root) / CANDIDATES_DIR
    else:
        allowlist_path = Path(allowlist_path)
        if repo_root is None:
            repo_root = _repo_root_from(allowlist_path)
        if config_path is None:
            config_path = Path(repo_root) / DEFAULT_CONFIG_REL
        if candidates_dir is None:
            candidates_dir = Path(repo_root) / CANDIDATES_DIR

    candidates_dir = Path(candidates_dir)
    candidate_dir = candidates_dir / candidate_id

    tests: list[dict] = []

    def _record(
        name: str, desc: str, passed: bool, detail: str, hard_failure: bool
    ) -> None:
        tests.append({
            "name": name,
            "description": desc,
            "passed": passed,
            "detail": detail,
            "hard_failure": hard_failure,
        })

    # Check the candidate directory exists.
    if not candidate_dir.is_dir():
        _record("SETUP", "candidate directory exists", False,
                f"candidate dir not found: {candidate_dir}", hard_failure=True)
        return {
            "passed": False,
            "tests": tests,
            "hard_failure": True,
        }

    patch_path = candidate_dir / "skill.patch"
    metadata_path = candidate_dir / "metadata.json"

    if not patch_path.is_file():
        _record("SETUP", "skill.patch exists", False,
                f"skill.patch not found in {candidate_dir}", hard_failure=True)
        return {"passed": False, "tests": tests, "hard_failure": True}

    patch_text = patch_path.read_text(encoding="utf-8")

    # Load metadata to get the skill_path.
    skill_path_str: str | None = None
    if metadata_path.is_file():
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            skill_path_str = metadata.get("skill_path")
        except (OSError, json.JSONDecodeError):
            pass
    if not skill_path_str:
        # Fall back to parsing the patch for the modified path.
        parsed = MC.parse_patch_paths(patch_text)
        if parsed:
            skill_path_str = parsed[0]["path"]

    # ── Load config limits ──────────────────────────────────────────────────────
    cfg = _load_optimization_config(Path(config_path) if config_path else Path("/nonexistent"))

    # ════════════════════════════════════════════════════════════════════════════
    # TEST MUT-001: patch only modifies allowlisted files
    # ════════════════════════════════════════════════════════════════════════════
    try:
        violations = MC.validate_candidate_patch(allowlist_path, patch_path)
        if violations:
            paths = [v["path"] for v in violations]
            _record("MUT-001", "patch only modifies allowlisted files", False,
                    f"non-allowlisted modifications: {paths}", hard_failure=True)
        else:
            _record("MUT-001", "patch only modifies allowlisted files", True,
                    "all modified paths are in the allowlist", hard_failure=True)
    except Exception as e:  # noqa: BLE001 — we want to catch any parser failure
        _record("MUT-001", "patch only modifies allowlisted files", False,
                f"allowlist check error: {e}", hard_failure=True)

    # ════════════════════════════════════════════════════════════════════════════
    # TEST MUT-002: patch does not touch safety-critical paths
    # (separate from MUT-001 so a safety violation gets its own reason)
    # ════════════════════════════════════════════════════════════════════════════
    safety_violations: list[dict] = []
    try:
        for entry in MC.parse_patch_paths(patch_text):
            allowed, reason = MC.check_mutation(allowlist_path, Path(entry["path"]))
            if not allowed and reason.startswith("safety-critical:"):
                safety_violations.append({"path": entry["path"], "reason": reason})
    except Exception as e:  # noqa: BLE001
        _record("MUT-002", "patch does not touch safety-critical paths", False,
                f"parse error: {e}", hard_failure=True)
    else:
        if safety_violations:
            _record("MUT-002", "patch does not touch safety-critical paths", False,
                    f"safety-critical modifications: {safety_violations}", hard_failure=True)
        else:
            _record("MUT-002", "patch does not touch safety-critical paths", True,
                    "no safety-critical paths touched", hard_failure=True)

    # ════════════════════════════════════════════════════════════════════════════
    # TEST SIZE-002: diff size under limit
    # (do this before SIZE-001/SIZE-003 so a huge patch fails fast)
    # ════════════════════════════════════════════════════════════════════════════
    diff_size = len(patch_text)
    if diff_size > cfg["max_diff_size"]:
        _record("SIZE-002", f"diff size under limit ({cfg['max_diff_size']} chars)", False,
                f"diff is {diff_size} chars (>{cfg['max_diff_size']})", hard_failure=True)
    else:
        _record("SIZE-002", f"diff size under limit ({cfg['max_diff_size']} chars)", True,
                f"diff is {diff_size} chars", hard_failure=True)

    # ════════════════════════════════════════════════════════════════════════════
    # TEST SIZE-003: skill length under limit
    # ════════════════════════════════════════════════════════════════════════════
    skill_text_after: str | None = None
    skill_len_detail = ""
    if skill_path_str:
        repo_root_path = Path(repo_root) if repo_root else _repo_root_from(allowlist_path)
        live_skill = repo_root_path / skill_path_str
        if live_skill.is_file():
            try:
                base_text = live_skill.read_text(encoding="utf-8")
                skill_text_after = _apply_patch_to_text(base_text, patch_text)
            except Exception as e:  # noqa: BLE001
                skill_len_detail = f"could not apply patch: {e}"
        else:
            # The skill file doesn't exist live — this could be a new
            # skill (creation). Treat the patch-added lines as the
            # skill content.
            added_lines = [ln[1:] for ln in patch_text.splitlines() if ln.startswith("+")
                           and not ln.startswith("+++")]
            if added_lines:
                skill_text_after = "\n".join(added_lines)
            else:
                skill_len_detail = "skill file not found and no added lines in patch"
    else:
        skill_len_detail = "no skill_path in metadata and no path in patch"

    if skill_text_after is not None:
        skill_len = len(skill_text_after)
        limit = cfg["max_skill_length"]
        desc = f"skill length under limit ({limit} chars)"
        if skill_len > limit:
            _record("SIZE-003", desc, False,
                    f"skill is {skill_len} chars after patch (>{limit})",
                    hard_failure=True)
        else:
            _record("SIZE-003", desc, True,
                    f"skill is {skill_len} chars after patch", hard_failure=True)
    else:
        limit = cfg["max_skill_length"]
        _record("SIZE-003", f"skill length under limit ({limit} chars)", False,
                f"could not measure skill length: {skill_len_detail}", hard_failure=True)

    # ════════════════════════════════════════════════════════════════════════════
    # TEST SIZE-001: complexity under ceiling (delta)
    # ════════════════════════════════════════════════════════════════════════════
    if skill_path_str and skill_text_after is not None:
        repo_root_path = Path(repo_root) if repo_root else _repo_root_from(allowlist_path)
        live_skill = repo_root_path / skill_path_str
        if live_skill.is_file():
            base_text = live_skill.read_text(encoding="utf-8")
            base_c = _cyclomatic_complexity(base_text)
            after_c = _cyclomatic_complexity(skill_text_after)
            delta = after_c - base_c
            if delta > cfg["complexity_ceiling"]:
                _record("SIZE-001",
                        f"complexity under ceiling (delta <= {cfg['complexity_ceiling']})", False,
                        f"complexity delta = +{delta} (>{cfg['complexity_ceiling']}) "
                        f"[base={base_c}, after={after_c}]",
                        hard_failure=True)
            else:
                _record("SIZE-001",
                        f"complexity under ceiling (delta <= {cfg['complexity_ceiling']})", True,
                        f"complexity delta = {delta:+d} [base={base_c}, after={after_c}]",
                        hard_failure=True)
        else:
            # New skill — absolute complexity is the metric.
            after_c = _cyclomatic_complexity(skill_text_after)
            ceil = cfg["complexity_ceiling"]
            new_desc = f"complexity under ceiling (<= {ceil} for new skill)"
            if after_c > ceil:
                _record("SIZE-001", new_desc, False,
                        f"new skill complexity = {after_c} (>{ceil})",
                        hard_failure=True)
            else:
                _record("SIZE-001", new_desc, True,
                        f"new skill complexity = {after_c}", hard_failure=True)
    else:
        _record("SIZE-001", "complexity under ceiling", False,
                "could not measure complexity (skill length test also failed)",
                hard_failure=True)

    # ════════════════════════════════════════════════════════════════════════════
    # TEST LEAK-001: no private label access
    # ════════════════════════════════════════════════════════════════════════════
    repo_root_path = Path(repo_root) if repo_root else _repo_root_from(allowlist_path)
    label_strings = _collect_private_label_strings(repo_root_path)
    if not label_strings:
        # No private labels exist — vacuously passes.
        _record("LEAK-001", "no private label access", True,
                "no private label files found (vacuous pass)", hard_failure=True)
    else:
        is_leak, detail = _check_leakage(patch_text, label_strings)
        if is_leak:
            _record("LEAK-001", "no private label access", False,
                    f"patch contains private label string: {detail!r}", hard_failure=True)
        else:
            _record("LEAK-001", "no private label access", True,
                    f"patch contains none of {len(label_strings)} private label strings",
                    hard_failure=True)

    # ─── Aggregate ─────────────────────────────────────────────────────────────
    all_passed = all(t["passed"] for t in tests)
    any_hard_fail = any(not t["passed"] and t["hard_failure"] for t in tests)

    result = {
        "passed": all_passed,
        "tests": tests,
        "hard_failure": any_hard_fail,
    }

    # Write the safety-checklist with results.
    checklist_path = candidate_dir / "safety-checklist.md"
    try:
        checklist_lines = [
            "# Safety checklist — candidate " + candidate_id,
            "",
            f"Overall passed: {all_passed}",
            f"Hard failure: {any_hard_fail}",
            "",
            "## Test results",
            "",
        ]
        for t in tests:
            mark = "[x]" if t["passed"] else "[ ]"
            checklist_lines.append(f"- {mark} {t['name']}: {t['description']}")
            if not t["passed"]:
                checklist_lines.append(f"    - {t['detail']}")
        checklist_lines.append("")
        checklist_lines.append(f"Status: {'PASS' if all_passed else 'FAIL'}"
                               f"{' (HARD FAILURE)' if any_hard_fail else ''}")
        checklist_path.write_text("\n".join(checklist_lines) + "\n", encoding="utf-8")
    except OSError:
        # Best-effort write — don't fail the test suite on a write error.
        pass

    return result


# ─── __all__ ─────────────────────────────────────────────────────────────────

__all__ = [
    "CANDIDATES_DIR",
    "stage_candidate",
    "run_safety_tests",
]
